# Generated by Django 4.2.2 on 2023-06-28 02:25

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_questao"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="resposta",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="pergunta",
                chained_model_field="pergunta",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.resposta",
            ),
            preserve_default=False,
        ),
    ]
