# Generated by Django 4.2.2 on 2023-06-28 14:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_questao_resposta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="questao",
            name="resposta",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="pergunta",
                chained_model_field="pergunta",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.resposta",
            ),
        ),
    ]
