# Generated by Django 4.2.2 on 2023-06-28 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_checklist_alter_questao_resposta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="user",
            new_name="user_str",
        ),
        migrations.AddField(
            model_name="checklist",
            name="user_obj",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
