# Generated by Django 4.2.2 on 2023-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_checklist_user_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="user_str",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
