# Generated by Django 4.2.2 on 2023-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_checklist_created_checklist_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
