# Generated by Django 4.2.2 on 2023-06-28 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_checklist_created_alter_checklist_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="user_obj",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="user_str",
        ),
    ]
